export const MAIN_PAGE_PATH = "/"
export const REGISTER_PAGE_PATH = "/register"
export const USER_PAGE_PATH = "/user/:externalId"
export const LIST_PAGE_PATH = "/list"
export const GRANT_COMMON_ACCESS_PATH = "/grant/:externalId"
export const ACCESSORS_LIST_PATH = "/access/:externalId"
export const ACCESSED_NOTES_PATH = "/accessed"