export const TOKEN_KEY = "currentToken"
export const LOGIN_KEY = "loginKey"
export const PASSWORD_KEY = "passwordKey"
export const ACCESS_TOKEN_EXPIRATION_TIME_KEY = "tokenExpirationTimeKey"
export const REFRESH_TOKEN = "refreshToken"
export const CURRENT_USER_DATA = "userExternalId"
export const LOCAL_FOLDER = "localFolder"